#' Sample Data from the Creativity Task
#'
#' A data set with responses generated by a member of the Kishida Lab.
#'
#' @format A data frame with 2112 rows and 2 variables:
#' \describe{
#'   \item{time}{Character String of Seconds since January, 1970}
#'   \item{data}{Participant data logged in the task}
#'   }
#'
#' @source Kishida Lab at Wake Forest School of Medicine
#'
"crt_data"
